New work
trpo2021/geometry-NaicikOne pull request #3
Opened 2021-04-12 08:19 UTC by NaicikOne

2021-04-18 15:04 UTC, kleineLi requested changes
Не соблюдена структура проекта.
Нет автоматической сборки и не создается статическая библиотека

2021-04-18 15:04 UTC, kleineLi commented on Makefile
> +geometry.c: $(OBJ)
у цели должно быть расширение `.exe`

2021-04-24 06:02 UTC, kleineLi requested changes
Всё ещё не подключён CI (не настроена автоматическая сборка, проверка форматирования).
Причина: ошибка в конфиг-файле (14 строка), нарушен синтаксис написания инструкций.

В корне репозитория находится файл с кодом, если он не нужен для сборки приложения, то его следует удалить.

После исправления замечаний, ветку new_work слейте в main без перемотки (с опцией `--no-ff`)

2021-04-24 06:39 UTC, NaicikOne commented
Я удалил лишний файл, о котором вы говорили. Но я не могу понять о каком конфиг файле идёт речь, и как исправить ошибку с CI. Я правильно понимаю, это слияние рабочих копий в общую основную ветвь разработки?

2021-04-24 07:29 UTC, kleineLi commented
@NaicikOne Изменения нужно вносить в локальном репозитории. 
При внесении изменений на гитхабе, перед отправкой изменений с локального репозитория обязательно выполняйте `git pull --rebase`

По ссылке показана ошибка и в каком файле нужно её исправить https://github.com/trpo2021/geometry-NaicikOne/actions/runs/779945733

2021-04-24 09:44 UTC, NaicikOne commented
сейчас и в репозитории на компьютере у меня ничего нет, и на Git'е файл удалён

2021-04-26 14:57 UTC, merged